### ISSUE TITLE
Issues with learning skills in DG

### ISSUE THREAD

**Issue by faceboogle** [soolar/sl_ascend#111]
Hello

I'm not sure what information would help, but the script seems to make strange and poor choices with skills in Dark Gyffte. Just been searching for a drum machine with only +35% item drop. I have plenty of HP so it could have learned Flock of Bats Form and Sharp Eyes. In fact I learned these manually and it went to the trouble of unlearning them...

I'm aware that it will be difficult to pick the best skills, especially when the player will have varying amounts of HP depending on runs completed and IoTMs. What information / feedback would help you to improve this?

Cheers
E

**Comment by soolar** [comment]
It's going to struggle in earlier runs no matter what and deciding which skills to learn when based on anything more complicated than a priority list (like, learning/unlearning the +item skills to learn other things when appropriate in lower hp runs) is more effort than I'm personally willing to put in since it doesn't matter on latter runs anyway.
