### ISSUE TITLE
Orc Chasm behavior

### ISSUE THREAD

**Issue by xande-1** [soolar/sl_ascend#113]
There are a couple of things that could be improved with how the script gets through the Orc Chasm
* It doesn't turn off the MCD for the chasm.  Since NC progress is based on how much it overkills the orcs by, reducing ML as much as possible will allow it to get the NC faster.
* Also, it tends to alternate Chill of the Tomb with Dark Feast.  The script does chill of the tomb, then on the next combat, since it's below max HP, it casts Dark Feast, which (with the cloake) kills the monster, getting no progress towards the NC.  (This is probably only an issue for early enough runs that the script doesn't buy Sanguine Magnetism yet.  Once it has Sanguine Magnetism, that should keep it topped up, and Dark Feasting won't be an issue.)

The ML issue is definitely worth fixing, since it affects all runs.  The Dark Feast issue will fix itself with enough starting HP.

**Comment by jaspercb** [comment]
* The first issue (turning off MCD) is fixed.
* I'm locally testing a solution to the second (Dark Feast usage) - just being less eager to use Dark Feast if we're in the Smut Orc Logging Camp and would otherwise use Chill of the Tomb. Currently testing a 60% HP cutoff, below which we'll revert to using Dark Feast.

Also just as a side note, this was a really high-quality bug report, so thanks for making it easier to get these fixes out! :)
