### ISSUE TITLE
Disabling automatic recovery

### ISSUE THREAD

**Issue by taltamir** [soolar/sl_ascend#148]
When you run sl_ascend it clears your recovery script (and attempts to restore it afterwards) because of compatibility issues between sl_ascend's built in recovery handling and 3rd party recovery scripts.

However, even without a recovery script there are mafia built in auto recovery options which also have compatibility issues. The only one which is automatically disabled is the option to automatically remove malignant status effects.

The rest remain at whatever setting they were last configured to. For example, I just had a case where presool was burning "excess mp" by casting a bunch of unnecessary buffs. Then mafia recovered said mp via doc galactic because of some leftover settings I had. This combination rapidly wasted all my meat and then even managed to get stuck in an infinite loop.

Whenever you run sl_ascend it should call
```
	set_property("hpAutoRecovery", "-1");
	set_property("hpAutoRecoveryTarget", "-1");
	set_property("mpAutoRecovery", "-1");
	set_property("mpAutoRecoveryTarget", "-1");
	set_property("manaBurningTrigger", "-1");
	set_property("manaBurningThreshold", "-1");
```
to disable those built in mafia features that sl_ascend is handling via its own logic.

Possibly first use get_property() to get the current values of the above and store them so that they can be automatically-restored when sl is done?

There is also "stop automation if HP is below %" option.
I am not sure what property that is, but that probably should be disabled too.

**Comment by Saklad5** [comment]
I wish there was a way to preserve user settings while running scripts like this. The issue is design: I have no idea how that would actually work, and I don’t think anyone else does either. They’re sort of mutually exclusive.

**Comment by soolar** [comment]
It should call `backupSetting("...", -1);` not `set_property("...", -1);`, because that way the properties will automatically be restored as long as you don't interrupt the script by hitting escape and use the soolascend relay script's interrupt button instead. I guess I can do this.

**Comment by soolar** [comment]
cd114a2cd49a8bbcc946ebfb8c54f7120bb779ce

**Comment by Saklad5** [comment]
Consider using a try/finally structure to ensure that the properties are reverted.

**Comment by jaspercb** [comment]
There is no try/finally construct in this scripting language. If you want the script to exit properly, please use sl_interrupt instead of hammering that ESCAPE key.

**Comment by Saklad5** [comment]
https://wiki.kolmafia.us/index.php?title=Control_Structures#try_.2F_finally

**Comment by taltamir** [comment]
what is sl_interrupt and how do I call it? is it a CLI command?

personally I have added a custom button to mafia that, when clicked, sends the CLI command "abort". It is my main tool for stopping scripts

**Comment by jaspercb** [comment]
Yes. Go to the drop-down relay menu and click soolascend. Then click sl_interrupt at the top of that page.

**Comment by taltamir** [comment]
It is problematic to attempt to navigate into a submenu while a script is running as it is constantly doing things in mafia itself. For example, instead of said submenu it could very well end up forwarding you to a fight, by the time it is done loading it in the relay browser the fight could be over and the script be doing other things.

Said submenu doesn't have a button to start the script either, only interrupt. So you are unlikely to be inside of it when you need it. (actually might want to add a start button there, right next to the interrupt button)

I think that dropdown should have a second thing put in it called sool_interrupt so you can access it without having to first process and load the submenu... or maybe make it that attempt to load the existing submenu while the sl_ascend is running automatically performs a proper interrupt?

That said, even then it will still be a relatively big delay between when you decide to abort and when you finally manage to do so (because the need to go into the drop down, select the right option, and then hit execute). If you are trying to abort there is usually an immediate reason for you to do so.

Is it possible to have it as a CLI command of
```
sl_ascend abort
```
because then it could be made into a custom button that you just need to click. Ideal for speedy yet still proper aborting

Actually, I have noticed some scripts seem to catch the CLI abort command and then do something afterwards. I think nemesis script is one of them... looking at it I think it is using a try/finally to do so.

Yea, I just tested it using a simple script. When you send the CLI abort command, it will indeed trigger the finally afterwards.

**Comment by Saklad5** [comment]
> It is problematic to attempt to navigate into a submenu while a script is running as it is constantly doing things in mafia itself. For example, instead of said submenu it could very well end up forwarding you to a fight, by the time it is done loading it in the relay browser the fight could be over and the script be doing other things.

Actually, the relay browser has its own queue of actions. Loading things like the submenu will _always_ succeed, even if you are literally in combat in the relay browser when you do so.

**Comment by Saklad5** [comment]
I don’t think there is currently a solution for this, but the real problem is running KoLmafia headlessly. There is no way to gracefully stop anything from the CLI (not to be confused with the gCLI). You can’t use relay overrides (obviously), and commands like “abort” and “exit” only get run when existing commands finish. There’s no equivalent to hitting “Esc”, either. The only way to stop it is to quit KoLmafia with SIGTERM or other Unix signals.

As I said, I’m fairly sure there is no way to address this until KoLmafia itself is changed to allow so.

**Comment by Saklad5** [comment]
Note that even the try/finally structure cannot guarantee execution. If the user presses “Esc” to abort the script, then presses it _again_ once it jumps to the “finally” clause, it’ll abort without finishing the clause. You could nest try/finally structures to catch _that_, but the same thing could happen a third time, and so forth.

**Comment by taltamir** [comment]
> I don’t think there is currently a solution for this, but the real problem is running KoLmafia headlessly. There is no way to gracefully stop anything from the CLI (not to be confused with the gCLI). You can’t use relay overrides (obviously), and commands like “abort” and “exit” only get run when existing commands finish. There’s no equivalent to hitting “Esc”, either. The only way to stop it is to quit KoLmafia with SIGTERM or other Unix signals.

what is the difference between gCLI and CLI? I always thought they are the same thing.

> Note that even the try/finally structure cannot guarantee execution. If the user presses “Esc” to abort the script, then presses it _again_ once it jumps to the “finally” clause, it’ll abort without finishing the clause. You could nest try/finally structures to catch _that_, but the same thing could happen a third time, and so forth.
> 
> In summary, try/finally should not be used as a substitute for storing settings in a dedicated backup setting, since it could still be interrupted.

While it cannot guarantee it in the case of the user sending multiple abort signals. Usually users send only 1 abort signal, also there is a small delay between each abort being sent and changing settings takes a fraction of a second. So there is a very good chance of try/finally successfully restoring the settings.

I agree with you that a dedicated backup setting would be even better. But I do think it is worth implementing try/finally

**Comment by taltamir** [comment]
> > It is problematic to attempt to navigate into a submenu while a script is running as it is constantly doing things in mafia itself. For example, instead of said submenu it could very well end up forwarding you to a fight, by the time it is done loading it in the relay browser the fight could be over and the script be doing other things.
> 
> Actually, the relay browser has its own queue of actions. Loading things like the submenu will _always_ succeed, even if you are literally in combat in the relay browser when you do so. It will never redirect anywhere.

Odd, I had experienced such redirect issues before. however it was not specifically with the drop down menu for scripts. I will test that one to see how it differs.

Anyways, having a start button next to the stop button would go a long way towards encouraging people to use that dropdown option.

actually, is it possible to, when starting to run sl_ascend have it open a relay browser specifically at the sl_ascend config page where there is the interrupt button?

**Comment by Saklad5** [comment]
> I have also noticed that there are some things that are unabortable except via terminating mafia. maximizing and... i think maybe possibly pvp cli command? or maybe the process of mafia executing the pre-ascension script when you click the gash (i think you can abort the preascension script, but it will then immediately ascend instead of it being aborted too)
> 
> I agree with you that a dedicated backup setting would be even better. But I do think it is worth implementing try/finally

First off, the _current_ approach uses backup settings, then uses them to restore the actual settings at the end of execution. I’m saying that we should keep that, since it guarantees that the previous settings are preserved (as the backup settings will never be removed before they are used). They should just be in a “finally” clause instead of being at the end of the main program body.

Second, those “unabortable” tasks basically use try/finally structures as well. When you abort them, they skip to the “finally” part. Aborting _again_ will cancel _that_.

**Comment by Saklad5** [comment]
> what is the difference between gCLI and CLI? I always thought they are the same thing.

CLI stands for “command line interface”. For a very long time, computers were basically entirely controlled through them. Nowadays, most primary interfaces are GUIs, which are “graphical user interfaces”. gCLI stands for “graphical CLI”, and it basically means it is a CLI in a GUI window. That is, a KoLmafia window. CLIs can often be easier to use than GUIs, especially if they are expected to do a wide variety of things. Imagine trying to use KoLmafia if every possible command was a menu item or button. It’d be a convoluted nightmare.

As for the difference: it is possible to use KoLmafia’s CLI directly, without opening any windows. You do so by passing the “--CLI” argument when launching the program from a command prompt. I use this feature extensively, since I often want to control things from my phone. A GUI designed for a cursor is often difficult to use on a touchscreen, and a GUI designed for touchscreens is difficult to use with cursors. CLIs are designed for keyboards alone, and everything is designed for keyboards, so they’re perfect for that. Of course, this isn’t particularly useful for playing the game normally, since it has graphics and such, but for running and controlling scripts like sl_ascend, it is sublime.

**Comment by Saklad5** [comment]
This is why you should _not_ launch the relay browser automatically. If you use a GUI element, that’s off-limits to anyone using just the CLI (like myself, often). It gets worse, however: I also synchronize my KoLmafia files with an instance running on an Ubuntu cloud server (which are _way_ cheaper than you might think). Since that server is inside a datacenter, it has a stupidly fast Internet connection, so scripts can execute as quickly as KoL servers can respond. That server is “headless”, meaning it doesn’t actually have a monitor or anything. It is only controlled by me, a very long way away, connecting to it and typing commands. If you try to launch the relay browser or any other GUI elements on that, it will fail: it doesn’t even have a screen to display things on.
