### ISSUE TITLE
New Script Update DIsables All Mafia MP and HP Recovery

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#153]
I don't know if this was intended but the latest script change is disabling all mafia MP and HP autorecovery

**Comment by taltamir** [comment]
It was intentional https://github.com/soolar/sl_ascend/issues/148#issue-429179677

sl_ascend has its own built in HP and MP recovery that can conflict and cause weird issues if you have a recovery script or mafia built in recovery. Which is why sl_ascend disables the setting for "automatically remove malignant effects" as well as automatically disables your custom recovery script. However it had previously left your mafia built in recovery on whatever setting they were initially (whether enabled or disabled, and without regards to what threshholds mafia had set).

Now it fully disables mafia automatic recovery to fully handle recovery on its own. Also, so long as it exits cleanly it should automatically restore the mafia settings related to recovery.

**Comment by txrangersxx** [comment]
Since this seems by design im closing
