### ISSUE TITLE
Attempts to go to Fantasy Realm results in infinite loop

### ISSUE THREAD

**Issue by michaeljhopkins** [soolar/sl_ascend#188]
The past 4 or 5 ascensions the script gets hung up when attempting to go to the Fantasy Realm for the token. The game informs informs that you are not high enough level. Manually opening the fantasy realm and click "Go in" resolves this issue

Is there a way the script can automatically override this, or should the fantasy realm be delayed in the timeline?

**Comment by jaspercb** [comment]
I think there's a Mafia setting that warns you when you would adventure in a high-level zone. Could you confirm that setting is disabled, and if it is, post the session logs that lead up to that point?

Either way, this can probably be fixed with a one-line "check that we're above level 6" check, or something similarly simple. Thanks for the report!

**Comment by michaeljhopkins** [comment]
Unsure if this is a mafia or a kol setting, I checked the box "Disable 'This area might be too tough for you' warnings". I'm assuming this will resolve it. Feel free to close this ticket

![Screen Shot 2019-04-27 at 1 38 01 PM](https://user-images.githubusercontent.com/4623657/56853767-cdc29800-68f1-11e9-9c12-f1dc99ad5b48.png)
