### ISSUE TITLE
Doesn't use the 4th May light sabre

### ISSUE THREAD

**Issue by faceboogle** [soolar/sl_ascend#203]
Just started HC DG ascension, script headed out with no weapon. It unequipped the light sabre when I grabbed it manually. It eventually found a Knob Goblin Scimitar and is using that. Is there a list of preferred weapons to update?

Cheers
E

Edit: I'm not talking about "using the force" as I expect that will take some time to work into the combat script. Just would like it to choose the best weapon in inventory

**Comment by jaspercb** [comment]
There's no Mafia support yet, which includes knowledge of the item's existence. I think (but haven't tested) that adding it to equipment.dat would crash anyone who *didn't* own a saber, since their Mafia wouldn't recognize the item name. Only 70% sure of this, though.

I'm not working on this until Mafia releases support, anyone else is free to work on this in the interim.

**Comment by soolar** [comment]
Yeah, I can say with 100% confidence that this would cause sl_ascend to fail to run for anyone without the saber until there's mafia support, which there is now, so it's supported now (just for equipping, though).

**Comment by Saklad5** [comment]
Could this be reopened? There’s KoLmafia support now.

**Comment by jaspercb** [comment]
We do equip it: https://github.com/soolar/sl_ascend/blob/master/RELEASE/data/sl_ascend_equipment.txt#L356

**Comment by Saklad5** [comment]
Oh, sorry, I didn’t notice this wasn’t about Use the Force.
