### ISSUE TITLE
"Recommended minimum stat" error not stopping script; endless looping

### ISSUE THREAD

**Issue by StewardOka** [soolar/sl_ascend#22]
The script was attempting to start the war, but ended up endlessly looping an attempt to adventure in a location that needed a manual override for not meeting the minimum stat recommendation.

It quickly flashed a message along the lines of "Minimum stat requirement not met, manually override warning and restart script." (sorry, not saved in the session log) before attempting to adventure again.  But the script didn't stop, so I didn't realize anything was wrong just by glancing at KoLMafia from time-to-time.

**Comment by MatthewDarling** [comment]
Seems like this might be related to the non-DG FantasyRealm problems mentioned in #61. I don't actually see any warnings like you've mentioned in the code, so that was probably a Mafia thing.

I'll try to trigger it manually and collect some info. KoLMafia wiki says [`adv1` returns `false` if it couldn't adventure](https://wiki.kolmafia.us/index.php?title=Adv1), so if all goes well, [checking `retval` here](https://github.com/MatthewDarling/sl_ascend/blob/master/RELEASE/scripts/sl_ascend/sl_adventure.ash#L45) should allow us to detect this.

Although, if we want to do something other than abort the script, this would get gnarly... We'd need to check the return value of `ccAdv` everywhere it's used. Which is a lot.

**Comment by MatthewDarling** [comment]
With 93 mysticality, trying FantasyRealm since it has a high requirement:

```
>  ash (adv1($location[The Bandit Crossroads], 1, ""))
Visit to FantasyRealm: The Bandit Crossroads in progress...
Your stats are too low for this location. Adventure manually to acknowledge or disable this warning.

Returned: false
```

And as you'd said, it didn't put anything in the session log. Since it specifically says "adventure manually to get past this", I guess we probably can't force the adventure to happen.

Meanwhile, this `false` value could mean things other than "mainstat too low". And KoLMafia doesn't know the right mainstat values:

```
> ash $location[The Bandit Crossroads]

Returned: The Bandit Crossroads
...
recommended_stat => 0
```

So we can't check that way :/ Wonder if it's worth mounting a campaign to get wiki data imported to fill in those numbers?

**Comment by soolar** [comment]
The fix here is to change your settings to disable the minimum stat requirement warnings.
