### ISSUE TITLE
Dumpster Fire vs Elf Operative question

### ISSUE THREAD

**Issue by Phate4569** [soolar/sl_ascend#259]
I notice the script uses Dumpster Fire alot. I'm wonderring why that is. I would have thought it would use Elf Operative on the off chance it gets a tryptophan dart.

**Comment by Saklad5** [comment]
The Elf Operative increases stats instead of restoring HP/MP. I think that is worthwhile, especially earlier in a run. Besides, the consumables granted by the Garbage Fire are obviously less important in TCRS.

Admittedly, all of the drops besides combat items are fairly valueless in TCRS. All food, booze, spleen items, and potions are equal in the eyes of the RNG (hard-coded effects aside), and equipment is only differentiated by the number of modifiers.

**Comment by soolar** [comment]
Elf Operative should generally be higher priority than Garbage Fire in the beta familiar handling, since I figured stats were better than regen most of the time. It'll still grab one drop from the Garbage Fire before switching to the Elf Operative though. Tryptophan dart doesn't currently actually get used though, but I guess I could add that.
