### ISSUE TITLE
Caution Mode for Level 13

### ISSUE THREAD

**Issue by Phate4569** [soolar/sl_ascend#262]
Using non-quest fights/statgain should be disallowed unless we absolutely need them once Level 13 is achieved. With Shinies it is WAY too easy to level quickly.

This includes:
NEP
FantasyRealm
GodLobster
Kramco
Voting Monster
LOV

**Comment by soolar** [comment]
For Voting Monsters it would be way too much trouble to determine whether we actually need the monster (ie for delay burning or LFM macrometeoriting) even though we're level 13. NEP still has moderately useful drops and meat. FantasyRealm is only used for the phat loot token, so I don't understand why it's listed there. GodLobster is a fair point, I'll disable that if you're 13 or higher. Kramco still gives sausage, so no. LOV gives chocolate or enamorang and a buff, so no.

Ultimately getting the instant karma for finishing a run at exactly level 13 isn't exactly an incredibly high priority in my opinion anyway. And when the changes to use maximizer based equipment finally gets finished it should make things better in this respect, since it will remove any emphasis from exp/ml once you hit 13.
