### ISSUE TITLE
Useless funkslinging of certain items

### ISSUE THREAD

**Issue by Saklad5** [soolar/sl_ascend#268]
There are a few items that should never be used twice with Ambidextrous Funkslinging, as their effects cannot be applied more than once. In particular, tangles of rat tails and cigarette lighters should never be used before another item, including themselves.

As of https://github.com/soolar/sl_ascend/commit/e6ca7105e8a94248966d25183570dc7c46f0deea, sl_ascend will nonetheless use two at once, wasting one of them (and therefore several adventures) for no reason.

**Comment by soolar** [comment]
If that's happening, it's a mafia bug, not an sl_ascend bug, in my opinion. sl_ascend just does `return "item " + $item[Tangle Of Rat Tails];` in its consult script as the only reference to tangles, so that's mafia adding an extra one automatically. There might be some way to tell mafia not to automatically do that for a specific invocation, but I'm not aware of it. Regardless, it does seem like a specific case where mafia shouldn't automatically funksling a second one.

**Comment by Saklad5** [comment]
Do you want to open this issue on the KoLmafia forums, or should I? Either way, this should probably be closed if it isn’t actually a glitch with anything in this repository.

**Comment by Saklad5** [comment]
OK, I figured out the issue. Line 726 of net/sourceforge/kolmafia/combat/CombatActionManager.java:
`if ( secondName.equals( "none" ) )
			{
				// Asking for no Funkslinging
				return first + ",-1";
			}
`
This seems like a really ridiculous implementation, but I guess you have to return “item tangle of rat tails, none” to avoid wasting it.

**Comment by soolar** [comment]
Alright, I'll do that then. Thanks!
