### ISSUE TITLE
Parse first Shen event as Ed

### ISSUE THREAD

**Issue by soolar** [soolar/sl_ascend#7]

**Comment by c0mp13371331337** [comment]
After some testing and discussion, we determined that the issue can be fixed by either manually setting the shenQuestItem in the CLI to the appropriate item, or by restarting Mafia.  Rinn said that it's an issue on the Mafia side, so a TRUE fix would require the HTML of the Shen NC to be submitted in a Bug Report against Mafia, but in the meantime, hitting the quest log with a visit_url() after the Shen NC and setting the shenQuestItem based on the scraped quest data should suffice.

**Comment by Malibu-Stacey** [comment]
https://kolmafia.us/showthread.php?23742-shenQuestItem-may-not-be-populated-the-first-time-you-meet-Shen-Copperhead

I had added the following locally in `L11_shenCopperhead()`
```
		item it = to_item(get_property("shenQuestItem"));
		**if (it == $item[none] && my_class() == $class[Ed])
		{
			// temp workaround until mafia bug is fixed - https://kolmafia.us/showthread.php?23742
			cli_execute("refresh quests");
			it = to_item(get_property("shenQuestItem"));
		}**
		location goal = $location[none];
```
but Darzil has made mafia do the same thing so I've never actually tried that change (my additions are in bold).

P.S. when mafia issues are found, please go report them on their forums. Even if you don't  have the HTML or whatever at least it lets them (or someone else like me) trace the problem.
