### ISSUE TITLE
In Vampire does not recognize Bonerdragon replacement being killed

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#81]
Visit to Cyrpt: Haert of the Cyrpt in progress...

[278] Haert of the Cyrpt
Encounter: The Haert of Darkness
Encounter: Jayden Harker
Round 0: txranger loses initiative!
Round 1: You lose 24 hit points
sl_combatHandler: 0
Round 1: txranger casts MICROMETEORITE!
Round 2: Jayden Belmont drops 17 attack power.
Round 2: Jayden Belmont drops 17 defense.
Round 2: txranger casts SING ALONG!
Round 3: You lose 22 hit points
Round 3: txranger casts CHILL OF THE TOMB!
Round 4: Jayden Belmont takes 247 damage.
Round 4: txranger wins the fight!
You gain 30 Meat
You acquire an item: red money bag
After Battle: You gain 16 Muscleboundness
After Battle: You gain 31 Enchantedness
After Battle: You gain 16 Smarm

Post Adventure done, beep.
Retrieving quest data...
Failed to kill bonerdagon

**Comment by taltamir** [comment]
I believe this is a mafia issue instead of script issue. Specifically with the preference
questL07Cyrptic
not correctly updating when the bonerdagon replacement is killed.

This variable has 4 possible states: unstarted, started, step1, finished
step1 = killed the bonerdagon but did not turn it in yet. the rest are self explanatory.

there are several other similar issues with mafia not correctly tracking quest status in vampyre at the moment which confuses ezandora's guide script as well.

**Comment by jaspercb** [comment]
Yeah. I tried adding a `refresh quests` call before checking the Cyrpt boss status, but it seems like that didn't work here, so I'm not sure.

**Comment by txrangersxx** [comment]
Can someone more educated in the working make a bug request or if one has already been made lets just wait

**Comment by jaspercb** [comment]
I have a mitigation here, where we visit the council before refreshing quest status and checking completion: https://github.com/soolar/sl_ascend/commit/0aa73e8bdc023cd00653e92308f22852e7c5893a

**Comment by txrangersxx** [comment]
Fixed and closing
