### ISSUE TITLE
Do not do neverending party if you are already at level 13

### ISSUE THREAD

**Issue by txrangersxx** [soolar/sl_ascend#93]
I know this is lots of free fights but after level 13 in most paths it doesn't make a difference since there really isn't much there

**Comment by jaspercb** [comment]
It's not costing turns, so I don't see this as super pressing. Is the main cost that you might have wanted to use it differently in aftercore?

**Comment by txrangersxx** [comment]
That is one reason, but you really don't need the stats if your already level 13

**Comment by taltamir** [comment]
While you do not need the stats, it gives you extra items and meat, and the extra stats don't actually hurt. So it is a waste to not do them.

The only reasons to not do it is to either save them for aftercore where you can use them more efficiently (better +item, +meat, and +mainstat for stat gains), or to avoid missing the 11 karma you get for being exactly level 13 when killing the naughty sorceress. But in that case you need some hefty programming to avoid this (taking into account estimated adv left to do and the gains they would give)...

If this gets implemented it should be as an option rather than always.

**Comment by jaspercb** [comment]
Taltamir, does KoLmafia know you always have access to the Neverending Party? There's a flag, like for charters.

**Comment by jaspercb** [comment]
But yeah, I mostly don't want to fix this for fear of knock-on effects in Big or other weird ascension paths.

**Comment by txrangersxx** [comment]
Im closing this I agree with leaving it in
